# Use postgres/example user/password credentials
services:

  db:
    image: postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
